### ISSUE TITLE
Error in `/opt/conda/bin/python': double free or corruption (fasttop):

### ISSUE THREAD

**Issue by Parisnewsy** [bindog/pytorch-model-parallel#2]
Can you provide your code running environment？
Thanks a lot!

**Comment by bindog** [comment]
Please don't use Anaconda, this error may caused by some unknown issues related to low level libraries.
you can use the following command to configure your environment(higher version of pytorch and torchvision is OK too)
```bash
pip3 install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

git clone https://github.com/NVIDIA/apex.git
cd apex
pip3 install -v --no-cache-dir ./
```
I will try to add a `requirement.txt` file in the future
