### ISSUE TITLE
partial fc

### ISSUE THREAD

**Issue by markncx** [bindog/pytorch-model-parallel#5]
partial pc可以尝试一下

**Comment by bindog** [comment]
本质上是一样的方法，所谓的"partial fc"方法在业内2018/2019年就有开始应用了（我司也在其中），我更愿意称之为一个trick；后来2020年DeepGlint把这个方法发表了论文而已，命名为"partial fc"

**Comment by markncx** [comment]
还有个问题问一下，你之前做模型并行，主要是为了face recognition还是image retrieval？id量很大的时候，是否尝试过triplet loss呢？我的任务里，triplet loss很难调work，请问有没有一些经验可以介绍一下。谢谢

**Comment by bindog** [comment]
人脸识别，triplet loss确实很难调，推荐用amsoftmax

**Comment by markncx** [comment]
> 人脸识别，triplet loss确实很难调，推荐用amsoftmax

谢谢！你做过image retrieval任务吗？工业数据太脏，triplet训各种各样的问题，很难work。但是，为了好扩展、显存友好，我们还是想用triplet。你在调triplet方法是否能给点宝贵的建议和经验呢？

**Comment by markncx** [comment]
能加个微信不，以后可以多交流一下。微信号：xiangqian_hust

**Comment by zhangkai-byte** [comment]
> 本质上是一样的方法，所谓的"partial fc"方法在业内2018/2019年就有开始应用了（我司也在其中），我更愿意称之为一个trick；后来2020年DeepGlint把这个方法发表了论文而已，命名为"partial fc"

Partial Fc 是分析出了模型并行的上限，类别数的增加同时增加GPU即使这样单卡显存还是要线性增长的，他们用近似的方法解决模型并行解决不了的**千万级id和亿级id**分类问题，只不过近似方法在现有公开的人脸训练集中会掉点，他们自己合并了一个大一点的人脸训练集来验证他们的方法。

**Comment by markncx** [comment]
> > 本质上是一样的方法，所谓的"partial fc"方法在业内2018/2019年就有开始应用了（我司也在其中），我更愿意称之为一个trick；后来2020年DeepGlint把这个方法发表了论文而已，命名为"partial fc"
> 
> Partial Fc 是分析出了模型并行的上限，类别数的增加同时增加GPU即使这样单卡显存还是要线性增长的，他们用近似的方法解决模型并行解决不了的**千万级id和亿级id**分类问题，只不过近似方法在现有公开的人脸训练集中会掉点，他们自己合并了一个大一点的人脸训练集来验证他们的方法。

赞同
